# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        channel-priority: strict
        show-channel-urls: true
        auto-update-conda: true

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda config --set always_yes yes
        conda install pytest pip 
        conda install -c conda-forge pyccl
        pip install .
  
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
